<?php

namespace AwardsMartFrontend\PrimarySiteBundle\Repository;

/**
 * HtmlPageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HtmlPageRepository extends \Doctrine\ORM\EntityRepository
{
}
