<?php

namespace AwardsMartFrontend\PrimarySiteBundle\Repository;

/**
 * LibraryImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LibraryImageRepository extends \Doctrine\ORM\EntityRepository
{
}
