<?php

namespace AwardsMartBackend\ProductsBundle\Repository;

/**
 * CategoryImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryImageRepository extends \Doctrine\ORM\EntityRepository
{
}
