<?php

namespace AwardsMartBackend\ProductsBundle\Repository;

use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * ProductAddonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductAddonRepository extends \Doctrine\ORM\EntityRepository
{
    public function findPaginatedAll($limit = 5, $page = 1)
    {
        $qb = $this->createQueryBuilder('a');
        $qb->andWhere('a.isActive = 1');
        $qb->addOrderBy("a.name","ASC");

        return $this->paginate($qb, $limit, $page);
    }

    /**
     * @param $dql
     * @param int $limit
     * @param int $page
     * @return Paginator
     *
     * This will create a Paginator instance with the right info.
     */
    public function paginate($dql, $limit = 5, $page = 1)
    {
        $paginator = new Paginator($dql);

        $paginator->getQuery()
            ->setFirstResult($limit * ($page - 1)) // Offset
            ->setMaxResults($limit); // Limit

        return $paginator;
    }
}
