<?php

namespace AwardsMartBackend\ProductsBundle\Repository;
use AwardsMartBackend\ProductsBundle\Entity\Category;
use AwardsMartBackend\ProductsBundle\Entity\Product;
use AwardsMartBackend\ProductsBundle\Entity\ProductOption;

/**
 * ProductOptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductOptionRepository extends \Doctrine\ORM\EntityRepository
{
    public function getMergedOptions(Category $category, Product $product)
    {
        $options_array = array();

        /** @var ProductOption $option */
        foreach( $product->getOptions() as $option )
        {
            $options_array[$option->getId()] = $option->getName();
        }

        /** @var ProductOption $option */
        foreach( $category->getOptions() as $option )
        {
            $options_array[$option->getId()] = $option->getName();
        }

        return $options_array;
    }
}
