<?php

namespace AwardsMartBackend\ProductsBundle\Repository;

/**
 * ProductExtraFeeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductExtraFeeRepository extends \Doctrine\ORM\EntityRepository
{
}
