<?php

namespace AwardsMartBackend\ProductsBundle\Repository;

/**
 * SizePriceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SizePriceRepository extends \Doctrine\ORM\EntityRepository
{
}
