<?php

namespace AwardsMartBackend\CustomerBundle\Repository;

/**
 * CartItemUploadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CartItemUploadRepository extends \Doctrine\ORM\EntityRepository
{
}
