<?php

namespace AwardsMartBackend\CustomerBundle\Repository;

/**
 * CartRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CartRepository extends \Doctrine\ORM\EntityRepository
{
    const LOGO_FEE = 14.95;

    const ENGRAVING_FEE = 5.0;

    const ENGRAVING_MAX_LINES = 5;
}
