<?php

namespace AwardsMartBackend\CustomerBundle\Repository;

/**
 * CustomerAddressRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerAddressRepository extends \Doctrine\ORM\EntityRepository
{
}
