# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    role_hierarchy:
        ROLE_SUPER_ADMIN:   ROLE_USER, ROLE_PRODUCTS, ROLE_CATEGORIES, ROLE_ORDERS, ROLE_PAGES

    encoders:
        AwardsMartBackend\AdminInterfaceBundle\Entity\User:
            algorithm: bcrypt

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory: ~
        awardsmart_db_provider:
            entity:
                class: AdminInterfaceBundle:User
                property: username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            form_login:
                login_path: admin.login
                check_path: admin.login
                provider: awardsmart_db_provider

            logout:
                path: /logout
                target: /

    access_control:
            - { path: ^/administrator/users, roles: ROLE_SUPER_ADMIN }
            - { path: ^/administrator/products, roles: ROLE_PRODUCTS }
            - { path: ^/administrator/addons, roles: ROLE_PRODUCTS }
            - { path: ^/administrator/categories, roles: ROLE_CATEGORIES }
            - { path: ^/administrator/cms-pages, roles: ROLE_PAGES }
            - { path: ^/administrator/orders, roles: ROLE_ORDERS }
            - { path: ^/administrator, roles: ROLE_USER }

