<?php

namespace Proxies\__CG__\AwardsMartBackend\ProductsBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ProductSize extends \AwardsMartBackend\ProductsBundle\Entity\ProductSize implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AwardsMartBackend\\ProductsBundle\\Entity\\ProductSize' . "\0" . 'id', '' . "\0" . 'AwardsMartBackend\\ProductsBundle\\Entity\\ProductSize' . "\0" . 'size', '' . "\0" . 'AwardsMartBackend\\ProductsBundle\\Entity\\ProductSize' . "\0" . 'units', '' . "\0" . 'AwardsMartBackend\\ProductsBundle\\Entity\\ProductSize' . "\0" . 'product', '' . "\0" . 'AwardsMartBackend\\ProductsBundle\\Entity\\ProductSize' . "\0" . 'prices'];
        }

        return ['__isInitialized__', '' . "\0" . 'AwardsMartBackend\\ProductsBundle\\Entity\\ProductSize' . "\0" . 'id', '' . "\0" . 'AwardsMartBackend\\ProductsBundle\\Entity\\ProductSize' . "\0" . 'size', '' . "\0" . 'AwardsMartBackend\\ProductsBundle\\Entity\\ProductSize' . "\0" . 'units', '' . "\0" . 'AwardsMartBackend\\ProductsBundle\\Entity\\ProductSize' . "\0" . 'product', '' . "\0" . 'AwardsMartBackend\\ProductsBundle\\Entity\\ProductSize' . "\0" . 'prices'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (ProductSize $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function resetPrices()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'resetPrices', []);

        return parent::resetPrices();
    }

    /**
     * {@inheritDoc}
     */
    public function addPrice(\AwardsMartBackend\ProductsBundle\Entity\SizePrice $price)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPrice', [$price]);

        return parent::addPrice($price);
    }

    /**
     * {@inheritDoc}
     */
    public function removePrice(\AwardsMartBackend\ProductsBundle\Entity\SizePrice $price)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePrice', [$price]);

        return parent::removePrice($price);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrices()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrices', []);

        return parent::getPrices();
    }

    /**
     * {@inheritDoc}
     */
    public function getProduct()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProduct', []);

        return parent::getProduct();
    }

    /**
     * {@inheritDoc}
     */
    public function setProduct($product)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProduct', [$product]);

        return parent::setProduct($product);
    }

    /**
     * {@inheritDoc}
     */
    public function removeProduct()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeProduct', []);

        return parent::removeProduct();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setSize($size)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSize', [$size]);

        return parent::setSize($size);
    }

    /**
     * {@inheritDoc}
     */
    public function getSize()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSize', []);

        return parent::getSize();
    }

    /**
     * {@inheritDoc}
     */
    public function setUnits($units)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUnits', [$units]);

        return parent::setUnits($units);
    }

    /**
     * {@inheritDoc}
     */
    public function getUnits()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUnits', []);

        return parent::getUnits();
    }

}
