<?php

namespace Proxies\__CG__\AwardsMartBackend\ProductsBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class SizePrice extends \AwardsMartBackend\ProductsBundle\Entity\SizePrice implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AwardsMartBackend\\ProductsBundle\\Entity\\SizePrice' . "\0" . 'id', '' . "\0" . 'AwardsMartBackend\\ProductsBundle\\Entity\\SizePrice' . "\0" . 'min', '' . "\0" . 'AwardsMartBackend\\ProductsBundle\\Entity\\SizePrice' . "\0" . 'max', '' . "\0" . 'AwardsMartBackend\\ProductsBundle\\Entity\\SizePrice' . "\0" . 'isSingle', '' . "\0" . 'AwardsMartBackend\\ProductsBundle\\Entity\\SizePrice' . "\0" . 'price', '' . "\0" . 'AwardsMartBackend\\ProductsBundle\\Entity\\SizePrice' . "\0" . 'size'];
        }

        return ['__isInitialized__', '' . "\0" . 'AwardsMartBackend\\ProductsBundle\\Entity\\SizePrice' . "\0" . 'id', '' . "\0" . 'AwardsMartBackend\\ProductsBundle\\Entity\\SizePrice' . "\0" . 'min', '' . "\0" . 'AwardsMartBackend\\ProductsBundle\\Entity\\SizePrice' . "\0" . 'max', '' . "\0" . 'AwardsMartBackend\\ProductsBundle\\Entity\\SizePrice' . "\0" . 'isSingle', '' . "\0" . 'AwardsMartBackend\\ProductsBundle\\Entity\\SizePrice' . "\0" . 'price', '' . "\0" . 'AwardsMartBackend\\ProductsBundle\\Entity\\SizePrice' . "\0" . 'size'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (SizePrice $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getSize()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSize', []);

        return parent::getSize();
    }

    /**
     * {@inheritDoc}
     */
    public function setSize($size)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSize', [$size]);

        return parent::setSize($size);
    }

    /**
     * {@inheritDoc}
     */
    public function removeSize()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeSize', []);

        return parent::removeSize();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setMin($min)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMin', [$min]);

        return parent::setMin($min);
    }

    /**
     * {@inheritDoc}
     */
    public function getMin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMin', []);

        return parent::getMin();
    }

    /**
     * {@inheritDoc}
     */
    public function setMax($max)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMax', [$max]);

        return parent::setMax($max);
    }

    /**
     * {@inheritDoc}
     */
    public function getMax()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMax', []);

        return parent::getMax();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsSingle($isSingle)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsSingle', [$isSingle]);

        return parent::setIsSingle($isSingle);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsSingle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsSingle', []);

        return parent::getIsSingle();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrice($price)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrice', [$price]);

        return parent::setPrice($price);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrice()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrice', []);

        return parent::getPrice();
    }

}
