<?php

namespace Proxies\__CG__\AwardsMartBackend\CustomerBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Customer extends \AwardsMartBackend\CustomerBundle\Entity\Customer implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AwardsMartBackend\\CustomerBundle\\Entity\\Customer' . "\0" . 'id', '' . "\0" . 'AwardsMartBackend\\CustomerBundle\\Entity\\Customer' . "\0" . 'name', '' . "\0" . 'AwardsMartBackend\\CustomerBundle\\Entity\\Customer' . "\0" . 'email', '' . "\0" . 'AwardsMartBackend\\CustomerBundle\\Entity\\Customer' . "\0" . 'phone', '' . "\0" . 'AwardsMartBackend\\CustomerBundle\\Entity\\Customer' . "\0" . 'eventDate', '' . "\0" . 'AwardsMartBackend\\CustomerBundle\\Entity\\Customer' . "\0" . 'time', '' . "\0" . 'AwardsMartBackend\\CustomerBundle\\Entity\\Customer' . "\0" . 'callbackTime', '' . "\0" . 'AwardsMartBackend\\CustomerBundle\\Entity\\Customer' . "\0" . 'cart', '' . "\0" . 'AwardsMartBackend\\CustomerBundle\\Entity\\Customer' . "\0" . 'addresses'];
        }

        return ['__isInitialized__', '' . "\0" . 'AwardsMartBackend\\CustomerBundle\\Entity\\Customer' . "\0" . 'id', '' . "\0" . 'AwardsMartBackend\\CustomerBundle\\Entity\\Customer' . "\0" . 'name', '' . "\0" . 'AwardsMartBackend\\CustomerBundle\\Entity\\Customer' . "\0" . 'email', '' . "\0" . 'AwardsMartBackend\\CustomerBundle\\Entity\\Customer' . "\0" . 'phone', '' . "\0" . 'AwardsMartBackend\\CustomerBundle\\Entity\\Customer' . "\0" . 'eventDate', '' . "\0" . 'AwardsMartBackend\\CustomerBundle\\Entity\\Customer' . "\0" . 'time', '' . "\0" . 'AwardsMartBackend\\CustomerBundle\\Entity\\Customer' . "\0" . 'callbackTime', '' . "\0" . 'AwardsMartBackend\\CustomerBundle\\Entity\\Customer' . "\0" . 'cart', '' . "\0" . 'AwardsMartBackend\\CustomerBundle\\Entity\\Customer' . "\0" . 'addresses'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Customer $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function addAddress(\AwardsMartBackend\CustomerBundle\Entity\CustomerAddress $addr)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAddress', [$addr]);

        return parent::addAddress($addr);
    }

    /**
     * {@inheritDoc}
     */
    public function removeAddress(\AwardsMartBackend\CustomerBundle\Entity\CustomerAddress $addr)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAddress', [$addr]);

        return parent::removeAddress($addr);
    }

    /**
     * {@inheritDoc}
     */
    public function getAddresses()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddresses', []);

        return parent::getAddresses();
    }

    /**
     * {@inheritDoc}
     */
    public function getCart()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCart', []);

        return parent::getCart();
    }

    /**
     * {@inheritDoc}
     */
    public function setCart(\AwardsMartBackend\CustomerBundle\Entity\Cart $cart)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCart', [$cart]);

        return parent::setCart($cart);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCart()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCart', []);

        return parent::removeCart();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', [$email]);

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhone($phone)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhone', [$phone]);

        return parent::setPhone($phone);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhone()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhone', []);

        return parent::getPhone();
    }

    /**
     * {@inheritDoc}
     */
    public function setEventDate($eventDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEventDate', [$eventDate]);

        return parent::setEventDate($eventDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getEventDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEventDate', []);

        return parent::getEventDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setTime($time)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTime', [$time]);

        return parent::setTime($time);
    }

    /**
     * {@inheritDoc}
     */
    public function getTime()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTime', []);

        return parent::getTime();
    }

    /**
     * {@inheritDoc}
     */
    public function setCallbackTime($callbackTime)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCallbackTime', [$callbackTime]);

        return parent::setCallbackTime($callbackTime);
    }

    /**
     * {@inheritDoc}
     */
    public function getCallbackTime()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCallbackTime', []);

        return parent::getCallbackTime();
    }

    /**
     * {@inheritDoc}
     */
    public function getShippingAddress()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShippingAddress', []);

        return parent::getShippingAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function getBillingAddress()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBillingAddress', []);

        return parent::getBillingAddress();
    }

}
