<?php

namespace Proxies\__CG__\AwardsMartBackend\CustomerBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class CustomerAddress extends \AwardsMartBackend\CustomerBundle\Entity\CustomerAddress implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AwardsMartBackend\\CustomerBundle\\Entity\\CustomerAddress' . "\0" . 'id', '' . "\0" . 'AwardsMartBackend\\CustomerBundle\\Entity\\CustomerAddress' . "\0" . 'firstName', '' . "\0" . 'AwardsMartBackend\\CustomerBundle\\Entity\\CustomerAddress' . "\0" . 'lastName', '' . "\0" . 'AwardsMartBackend\\CustomerBundle\\Entity\\CustomerAddress' . "\0" . 'address', '' . "\0" . 'AwardsMartBackend\\CustomerBundle\\Entity\\CustomerAddress' . "\0" . 'city', '' . "\0" . 'AwardsMartBackend\\CustomerBundle\\Entity\\CustomerAddress' . "\0" . 'phone', '' . "\0" . 'AwardsMartBackend\\CustomerBundle\\Entity\\CustomerAddress' . "\0" . 'phoneAlt', '' . "\0" . 'AwardsMartBackend\\CustomerBundle\\Entity\\CustomerAddress' . "\0" . 'zipCode', '' . "\0" . 'AwardsMartBackend\\CustomerBundle\\Entity\\CustomerAddress' . "\0" . 'state', '' . "\0" . 'AwardsMartBackend\\CustomerBundle\\Entity\\CustomerAddress' . "\0" . 'role', '' . "\0" . 'AwardsMartBackend\\CustomerBundle\\Entity\\CustomerAddress' . "\0" . 'customer'];
        }

        return ['__isInitialized__', '' . "\0" . 'AwardsMartBackend\\CustomerBundle\\Entity\\CustomerAddress' . "\0" . 'id', '' . "\0" . 'AwardsMartBackend\\CustomerBundle\\Entity\\CustomerAddress' . "\0" . 'firstName', '' . "\0" . 'AwardsMartBackend\\CustomerBundle\\Entity\\CustomerAddress' . "\0" . 'lastName', '' . "\0" . 'AwardsMartBackend\\CustomerBundle\\Entity\\CustomerAddress' . "\0" . 'address', '' . "\0" . 'AwardsMartBackend\\CustomerBundle\\Entity\\CustomerAddress' . "\0" . 'city', '' . "\0" . 'AwardsMartBackend\\CustomerBundle\\Entity\\CustomerAddress' . "\0" . 'phone', '' . "\0" . 'AwardsMartBackend\\CustomerBundle\\Entity\\CustomerAddress' . "\0" . 'phoneAlt', '' . "\0" . 'AwardsMartBackend\\CustomerBundle\\Entity\\CustomerAddress' . "\0" . 'zipCode', '' . "\0" . 'AwardsMartBackend\\CustomerBundle\\Entity\\CustomerAddress' . "\0" . 'state', '' . "\0" . 'AwardsMartBackend\\CustomerBundle\\Entity\\CustomerAddress' . "\0" . 'role', '' . "\0" . 'AwardsMartBackend\\CustomerBundle\\Entity\\CustomerAddress' . "\0" . 'customer'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (CustomerAddress $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getCustomer()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCustomer', []);

        return parent::getCustomer();
    }

    /**
     * {@inheritDoc}
     */
    public function setCustomer(\AwardsMartBackend\CustomerBundle\Entity\Customer $customer)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCustomer', [$customer]);

        return parent::setCustomer($customer);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCustomer()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCustomer', []);

        return parent::removeCustomer();
    }

    /**
     * {@inheritDoc}
     */
    public function setFirstName($firstName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFirstName', [$firstName]);

        return parent::setFirstName($firstName);
    }

    /**
     * {@inheritDoc}
     */
    public function getFirstName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFirstName', []);

        return parent::getFirstName();
    }

    /**
     * {@inheritDoc}
     */
    public function setLastName($lastName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLastName', [$lastName]);

        return parent::setLastName($lastName);
    }

    /**
     * {@inheritDoc}
     */
    public function getLastName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLastName', []);

        return parent::getLastName();
    }

    /**
     * {@inheritDoc}
     */
    public function setAddress($address)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAddress', [$address]);

        return parent::setAddress($address);
    }

    /**
     * {@inheritDoc}
     */
    public function getAddress()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddress', []);

        return parent::getAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function setCity($city)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCity', [$city]);

        return parent::setCity($city);
    }

    /**
     * {@inheritDoc}
     */
    public function getCity()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCity', []);

        return parent::getCity();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhone($phone)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhone', [$phone]);

        return parent::setPhone($phone);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhone()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhone', []);

        return parent::getPhone();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhoneAlt($phoneAlt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhoneAlt', [$phoneAlt]);

        return parent::setPhoneAlt($phoneAlt);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhoneAlt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhoneAlt', []);

        return parent::getPhoneAlt();
    }

    /**
     * {@inheritDoc}
     */
    public function setZipCode($zipCode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setZipCode', [$zipCode]);

        return parent::setZipCode($zipCode);
    }

    /**
     * {@inheritDoc}
     */
    public function getZipCode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getZipCode', []);

        return parent::getZipCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setState($state)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setState', [$state]);

        return parent::setState($state);
    }

    /**
     * {@inheritDoc}
     */
    public function getState()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getState', []);

        return parent::getState();
    }

    /**
     * {@inheritDoc}
     */
    public function setRole($role)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRole', [$role]);

        return parent::setRole($role);
    }

    /**
     * {@inheritDoc}
     */
    public function getRole()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRole', []);

        return parent::getRole();
    }

}
